package com.lazydrop.modules.websocket;

public enum MessageType {
    FILE_UPLOAD_STARTED,
    FILE_UPLOADED,
    FILE_DOWNLOAD_STARTED,
    FILE_DOWNLOADED,
    FILE_DELETED,

    DROP_SESSION_CREATED,
    DROP_SESSION_EXPIRED,
    DROP_SESSION_CLOSED,
    DROP_SESSION_JOINED,
    DROP_SESSION_FILES_CLEANED,
    PEER_JOINED,
    PEER_LEFT,

    SESSION_NOTE_CREATED,
}
